<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH4lZg7g\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH4lZg7g/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH4lZg7g.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH4lZg7g\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerH4lZg7g\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'H4lZg7g',
    'container.build_id' => '0e0cbe31',
    'container.build_time' => 1582987374,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH4lZg7g');
