<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWATQpXc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWATQpXc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWATQpXc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWATQpXc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWATQpXc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WATQpXc',
    'container.build_id' => '0b998ff7',
    'container.build_time' => 1582984920,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWATQpXc');
